# Generated by Django 2.1.1 on 2020-02-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=2000)),
                ('output', models.CharField(max_length=2000)),
                ('jsonResponse', models.TextField()),
            ],
        ),
    ]
